"""empty message

Revision ID: f9d68e59a145
Revises: 
Create Date: 2020-04-27 17:52:36.136931

"""
from alembic import op
import sqlalchemy as sa

import app


# revision identifiers, used by Alembic.
revision = 'f9d68e59a145'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.UnicodeText(), nullable=False),
    sa.Column('email', app.models.util.EmailType(length=255), nullable=False),
    sa.Column('password', sa.Unicode(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
